### ISSUE TITLE
Ignore .pyc files

### ISSUE THREAD

**Issue by hellsan631** [plyte/Creep-My-Score#1]
Compiled files are not needed in source code, and can be a source of headache for merging purposes.

Here is a recommended list of things to add to the gitignore.
http://stackoverflow.com/questions/3719243/recommended-gitignore-file-for-python-projects

to remove the .pyc file, you must first delete it locally, commit and push the removal, then add it to the ignore.

:)

**Comment by plyte** [comment]
Thanks! I'll get to work on that.

**Comment by plyte** [comment]
Completed
